import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'
import fg from "fast-glob"
import fs from "node:fs"
import path from "node:path"
import sharp from "sharp"


function galleryManifestPlugin() {
  const galleriesRoot = path.resolve(process.cwd(), 'src/assets/galleries');
  const outFile = path.resolve(process.cwd(), 'src/generated/galleryManifest.js');

  async function buildManifestModule() {
    // Find all images under src/assets/galleries
    const files = await fg("**/*.{jpg,JPG,jpeg,png,webp}", {
      cwd: galleriesRoot,
      onlyFiles: true,
      absolute: true,
    });

    // Compute image dimensions
    const entries = [];
    for(const abs of files) {
      const relFromGalleries = path.relative(galleriesRoot, abs).replace(/\\/g, "/");
      const slug = relFromGalleries.split('/')[0];
      const relFromSrc = `assets/galleries/${relFromGalleries}`;
      const vitePath = `/src/${relFromSrc}`;

      let w = 0, h = 0;
      try {
        const meta = await sharp(abs).metadata();

        w = meta.width ?? 0;
        h = meta.height ?? 0;

        // EXIF orientation - some images use metadata to rotate the image, resulting in incorrect
        // layouts - so we must correct this
        const orientation = meta.orientation ?? 1;
        if([5, 6, 7, 8].includes(orientation)) {
          [w,h] = [h,w];
        }
      } 
      catch {}

      entries.push({ slug, vitePath, w, h });
    }

    // Ensure folder path exists
    fs.mkdirSync(path.dirname(outFile), { recursive: true });

    // Generate JS module, where:
    // - import.glob.meta eagerly resolves final asset URLs in dev & build
    // - Precomputed w/h is attached for instant gallery layout
    const code = `
    // AUTO-GENERATED by galleryManifestPlugin. Do not edit.
    const urls = import.meta.glob(
      '/src/assets/galleries/**/*.{png,jpg,JPG,jpeg,webp}',
      { eager: true, query: '?url', import: 'default' }
    );

    export const galleryManifest = ${JSON.stringify(
      entries.reduce((acc, e) => {
        (acc[e.slug] ||= []).push({ path: e.vitePath, w: e.w, h: e.h });
        return acc;
      }, {}),
      null,
      2
    )};

    // Map file path -> final URL (hashed in build)
    for (const slug of Object.keys(galleryManifest)) {
      galleryManifest[slug] = galleryManifest[slug].map((x) => ({
        src: urls[x.path],
        w: x.w,
        h: x.h,
        o: x.w >= x.h ? 'L' : 'P'
      }))
      .filter((x) => !!x.src);
    }`;

    fs.writeFileSync(outFile, code, "utf8");
  }

  return {
    name: "gallery-manifest",
    async buildStart() {
      await buildManifestModule();
    },
    async configureServer(server) {
      buildManifestModule();

      // Explicitly ignore the outputted file
      server.watcher.unwatch(outFile);

      const onChange = async(p) => {
        if(!p.includes(`${path.sep}src${path.sep}assets${path.sep}galleries${path.sep}`)) return;
        await buildManifestModule();
      }

      // Regenerate on changes during dev
      server.watcher.on("add", onChange);
      server.watcher.on("change", onChange);
      server.watcher.on("unlink", onChange);
    },
  };
}


// https://vite.dev/config/
export default defineConfig({
  plugins: [react(), tailwindcss(), galleryManifestPlugin()],
})
